### ISSUE TITLE
remote mlt init failed

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#123]
This happened to @mas-dse-greina :

```
ganthony-mac01:mlt ganthony$ rm -rf tony
ganthony-mac01:mlt ganthony$ mlt init tony
Traceback (most recent call last):
  File "/Users/ganthony/Documents/mlt/mlt/commands/init.py", line 51, in action
    shutil.copytree(templates_directory, self.app_name)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 185, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/jk3d5w8n14v41py769kbky000000gp/T/tmpoCXSkC/mlt-templates/hello-world'
Traceback (most recent call last):
  File "/Users/ganthony/Documents/mlt/.venv/bin/mlt", line 11, in <module>
    sys.exit(main())
  File "/Users/ganthony/Documents/mlt/mlt/main.py", line 117, in main
    run_command(args)
  File "/Users/ganthony/Documents/mlt/mlt/main.py", line 77, in run_command
    CommandClass(args).action()
  File "/Users/ganthony/Documents/mlt/mlt/commands/init.py", line 65, in action
    sys.exit(1)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ganthony/Documents/mlt/mlt/utils/git_helpers.py", line 36, in clone_repo
    shutil.rmtree(destination)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 253, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 251, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/jk3d5w8n14v41py769kbky000000gp/T/tmpoCXSkC'
ganthony-mac01:mlt ganthony$
```

but running with a local mlt worked:

```
ganthony-mac01:mlt ganthony$ mlt template list --template-repo=$(PWD)
Template        Description
--------------  --------------------------------------------------------------------------------------------------
hello-world     A TensorFlow python HelloWorld example run through Kubernetes Jobs.
pytorch         Sample distributed application taken from http://pytorch.org/tutorials/intermediate/dist_tuto.html
tf-distributed  A distributed TensorFlow matrix multiplication run through the TensorFlow Kubernetes Operator.
ganthony-mac01:mlt ganthony$ cd ..
ganthony-mac01:Documents ganthony$ pwd
/Users/ganthony/Documents
ganthony-mac01:Documents ganthony$ mlt init tony --template-repo=$(PWD)/mlt --template=tf-distributed
[master (root-commit) 7727353] Initial commit.
 7 files changed, 259 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Dockerfile
 create mode 100644 Makefile
 create mode 100644 README.md
 create mode 100644 k8s-templates/tfjob.yaml
 create mode 100644 main.py
 create mode 100644 requirements.txt

ganthony-mac01:Documents ganthony$ mlt build
This command requires you to be in an `mlt init` built directory.
ganthony-mac01:Documents ganthony$ cd tony
ganthony-mac01:tony ganthony$ mlt build
Starting build tony:1a59c0dc-5423-4cca-9cc8-58962f9436de
Building / (Elapsed Time: 0:00:00)
docker build --build-arg HTTP_PROXY=http://proxy-chain.intel.com:911 --build-arg HTTPS_PROXY=http://proxy-chain.intel.com:912 --build-arg http_proxy=http://proxy-chain.intel.com:911 --build-arg https_proxy= -t tony:1a59c0dc-5423-4cca-9cc8-58962f9436de .

Building | (Elapsed Time: 0:00:00)
ganthony-mac01:tony ganthony$ docker
```

**Comment by ashahba** [comment]
This should be fixed now specially after #168 was merged.

**Comment by dmsuehir** [comment]
I will follow up with @mas-dse-greina to see if this is still an issue

**Comment by mas-dse-greina** [comment]
No this is fixed.

Thanks gang.

-Tony
