### ISSUE TITLE
mlt init error if no gcloud and no `--registry`

### ISSUE THREAD

**Issue by dmsuehir** [IntelAI/mlt#259]
This issue was found when we were working with Seetha on the 5-node bare metal cluster.  If `mlt init` did not have a `--registry` specified, then MLT tries to use gcloud to get the project name to use that container registry.  However, if gcloud isn't on the host, then it errors in a way that does not tell the user what went wrong.

```
$mlt init myapp --template=hello-world
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/mlt/commands/init.py", line 66, in action
   data = self._build_mlt_json(template_params)
 File "/usr/lib/python2.7/site-packages/mlt/commands/init.py", line 87, in _build_mlt_json
   "value(core.project)"])
 File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
   process = Popen(stdout=PIPE, *popenargs, **kwargs)
 File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
   errread, errwrite)
 File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
   raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by tonyreina** [comment]
It would be great to have it check the environment for the registry and repo parameters first. This way for the baremetal cluster we don't have to specify the local registry every time we do an `mlt init`.
