### ISSUE TITLE
MLT logs error with python 3

### ISSUE THREAD

**Issue by dmsuehir** [IntelAI/mlt#278]
```[bduser@lancelot24 micah-demo]$ mlt deploy -l
Pushing  | (Elapsed Time: 0:01:19)
Pushed to gcr.io/constant-cubist-173123/micah-demo:8ab55b02-b014-432f-9c08-008188cf5e09
Deploying gcr.io/constant-cubist-173123/micah-demo:8ab55b02-b014-432f-9c08-008188cf5e09

Inspect created objects by running:
$ kubectl get --namespace=bduser all

Checking for pod(s) readiness
Traceback (most recent call last):
  File "/home/bduser/anaconda3/bin/mlt", line 11, in <module>
    sys.exit(main())
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/main.py", line 157, in main
    run_command(args)
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/main.py", line 100, in run_command
    CommandClass(args).action()
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/commands/deploy.py", line 55, in action
    self._tail_logs()
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/commands/deploy.py", line 309, in _tail_logs
    log_helpers.call_logs(self.config, self.args)
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/utils/log_helpers.py", line 54, in call_logs
    running = check_for_pods_readiness(namespace, prefix, retires)
  File "/home/bduser/anaconda3/lib/python3.6/site-packages/mlt/utils/log_helpers.py", line 116, in check_for_pods_readiness
    if filter_tag in pod:
TypeError: a bytes-like object is required, not 'str'```

**Comment by dmsuehir** [comment]
@karthikvadla

**Comment by dmsuehir** [comment]
Fix for this was merged: https://github.com/IntelAI/mlt/pull/279
