### ISSUE TITLE
Unable to deploy horovod with tail option

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#337]
```
Checking for pod(s) readiness
Traceback (most recent call last):
  File "/Users/robertso/Nervana/mlt/.venv3/bin/mlt", line 11, in <module>
    load_entry_point('mlt==0.1.2+57.g3a17d3b.dirty', 'console_scripts', 'mlt')()
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/main.py", line 190, in main
    run_command(args)
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/main.py", line 129, in run_command
    CommandClass(args).action()
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/commands/deploy.py", line 63, in action
    self._tail_logs()
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/commands/deploy.py", line 368, in _tail_logs
    log_helpers.call_logs(self.config, self.args)
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/utils/log_helpers.py", line 57, in call_logs
    running = check_for_pods_readiness(namespace, prefix, retires)
  File "/Users/robertso/Nervana/mlt/.venv3/lib/python3.6/site-packages/mlt/utils/log_helpers.py", line 114, in check_for_pods_readiness
    if filter_tag.encode('utf-8') in pod.encode('utf-8'):
AttributeError: 'bytes' object has no attribute 'encode'
```
I ran `mlt deploy -l` using `python3`

**Comment by s1113950** [comment]
Fixed already, unable to repro
