### ISSUE TITLE
`kubectl delete` call is failing in e2e tests sometimes

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#361]
See https://circleci.com/gh/IntelAI/mlt/1668?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
failed test. 

`kubectl --namespace root... delete -f k8s` failed with error: `you must provide one or more resources by argument or filename...`

Related issues on kubernetes:
https://github.com/kubernetes/kubernetes/issues/10853
https://github.com/kubernetes/kubernetes/issues/19767
supposed to have been fixed though...

From @nqn :
To rule out that it is thinking the `root-ahell351d` is a object name. You _could_ do `--namespace=root-ahell351d` (with the equal sign)
Or, you can check the content in the folder and make sure every file have a well formed name.

So we should probably do these things so we don't get occasional fails in e2e tests

**Comment by s1113950** [comment]
I just reproduced this!!
```
robertso@robertso-mac02:/tmp/wat$ mlt undeploy
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
Traceback (most recent call last):
  File "/Users/robertso/Nervana/mlt/.venv3/bin/mlt", line 11, in <module>
    load_entry_point('mlt==0.2.1+80.g90062cc', 'console_scripts', 'mlt')()
  File "/Users/robertso/Nervana/mlt/mlt/main.py", line 212, in main
    run_command(args)
  File "/Users/robertso/Nervana/mlt/mlt/main.py", line 134, in run_command
    CommandClass(args).action()
  File "/Users/robertso/Nervana/mlt/mlt/commands/undeploy.py", line 60, in action
    self._undeploy_jobs(namespace, jobs, all_jobs=True)
  File "/Users/robertso/Nervana/mlt/mlt/commands/undeploy.py", line 90, in _undeploy_jobs
    raise_on_failure=True)
  File "/Users/robertso/Nervana/mlt/mlt/utils/process_helpers.py", line 31, in run
    raise e
  File "/Users/robertso/Nervana/mlt/mlt/utils/process_helpers.py", line 28, in run
    output = check_output(command, cwd=cwd).decode("utf-8")
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--namespace', 'robertso', 'delete', '-f', 'k8s', '--recursive']' returned non-zero exit status 1.
```
I deployed a `horovod` job
```
robertso@robertso-mac02:/tmp/wat$ ls k8s
total 0
drwxr-xr-x   3 robertso  102 Aug 30 14:18 .
drwxr-xr-x  28 robertso  952 Aug 30 14:18 ..
drwxr-xr-x   2 robertso   68 Aug 30 14:18 wat-7cc105f3-290c-44a0-9a1a-bcb97e8b005f
```
I have a job still there, but horovod doesn't use templates.

Issue was that `files.is_custom()` wasn't returning true, even though horovod is classified as a custom job because it has `undeploy:` in the makefile, so this was being called:
```
["kubectl", "--namespace", namespace, "delete", "-f",
                 "k8s", "--recursive"],
                raise_on_failure=True)
```
rather than the custom undeploy logic.

In the `is_custom` function I found:
```
(Pdb) cwd
'k8s/wat-7cc105f3-290c-44a0-9a1a-bcb97e8b005f'
```
```
(Pdb) makefile_location
'k8s/wat-7cc105f3-290c-44a0-9a1a-bcb97e8b005f/Makefile'
```
but the folder was empty! So it was like the job was half-undeployed

**Comment by s1113950** [comment]
Can't repro anymore, closing
