### ISSUE TITLE
Codec issues with template substitution

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#415]
```
sleishma   scott/resnet  …  k8s-scale-workloads  resnet-i1k  code  python --version
Python 2.7.15
 sleishma   scott/resnet  …  k8s-scale-workloads  resnet-i1k  code  mlt --version
ML Container Templates Version 0.2.1
 sleishma   scott/resnet  …  k8s-scale-workloads  resnet-i1k  code  mlt deploy --no-push
Skipping image push
Deploying gcr.io/constant-cubist-173123/dist-resnet:78c7d8ee-8bfb-47ef-bd64-7fd24fb60ecb
Traceback (most recent call last):
  File "/usr/local/bin/mlt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mlt/main.py", line 189, in main
    run_command(args)
  File "/usr/local/lib/python2.7/site-packages/mlt/main.py", line 128, in run_command
    CommandClass(args).action()
  File "/usr/local/lib/python2.7/site-packages/mlt/commands/deploy.py", line 61, in action
    self._deploy_new_container()
  File "/usr/local/lib/python2.7/site-packages/mlt/commands/deploy.py", line 149, in _deploy_new_container
    remote_container_name=remote_container_name)
  File "/usr/local/lib/python2.7/site-packages/mlt/commands/deploy.py", line 187, in _default_deploy
    **config_helpers.get_template_parameters(self.config))
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 17: ordinal not in range(128)
```

mlt.json:
```
{
  "name": "dist-resnet",
  "template_name": "tf-dist-mnist",
  "namespace": "scott",
  "template_git_sha": "ecc5eed5151a15ac554340eea2a0f69abaeebdbf",
  "registry": "gcr.io/constant-cubist-173123",
  "template_parameters": {
    "num_master": 1,
    "num_ps": 1,
    "num_workers": 1,
    "master_instance_type": "n1-standard-8",
    "ps_instance_type": "n1-standard-8",
    "worker_instance_type": "n1-standard-8",
    "debug_on_fail": "False",
    "dataset_disk": "imagenet1k",
    "dataset_size": "150G",
    "dataset_pv_name": "i1k-pv",
    "dataset_pvc_name": "i1k-pvc",
    "dataset_fstype": "ext4",
    "dataset_mount": "/i1k"
  }
}
```
job.yaml:
```
apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"                       
metadata:                           
  name: $app                                
spec:                           
  replicaSpecs:        
    - replicas: $num_master
      tfReplicaType: "MASTER"
      template:
        spec:        
          containers:      
            - image: $image     
              name: "tensorflow"    
          restartPolicy: "OnFailure"
          nodeSelector:                                        
            beta.kubernetes.io/instance-type: $master_instance_type        
    - replicas: $num_workers
      tfReplicaType: "WORKER"
      template:
        spec:
          containers:
            - image: $image
              name: "tensorflow"
              volumeMounts:
                - mountPath: $dataset_mount
                  name: "resnet-dataset"
          restartPolicy: "OnFailure"
          nodeSelector:
            beta.kubernetes.io/instance-type: $worker_instance_type
          volumes:
            - name: "resnet-dataset"
              persistentVolumeClaim:
                claimName: $dataset_pvc_name
                readOnly: "true"
    - replicas: $num_ps
      tfReplicaType: "PS"
      template:
        spec:
          containers:
            - image: $image
              name: "tensorflow"
          restartPolicy: "OnFailure"
          nodeSelector:
            beta.kubernetes.io/instance-type: $ps_instance_type
```

**Comment by ashahba** [comment]
So this could be something specific to @scttl 's setup.
I just tried his code base and I was able to deploy successfully:

```
$ mlt deploy
Pushing scott-unet |##################################################################################################################| (ETA:  00:00:00) 
Pushed scott-unet to gcr.io/constant-cubist-173123/scott-unet:7020d2c6-cd73-40f4-b5fc-4ab7067a3111
Deploying gcr.io/constant-cubist-173123/scott-unet:7020d2c6-cd73-40f4-b5fc-4ab7067a3111
level=info msg="Updating configmaps scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-assets"
level=info msg=" Creating non-existent configmaps scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-assets"
level=info msg="Updating services scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg=" Creating non-existent services scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg="Updating serviceaccounts scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg=" Creating non-existent serviceaccounts scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg="Updating clusterrolebindings scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg=" Creating non-existent clusterrolebindings scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c"
level=info msg="Updating pods scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-master"
level=info msg=" Creating non-existent pods scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-master"
level=info msg="Updating pods scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-worker-0"
level=info msg=" Creating non-existent pods scott.scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-worker-0"

Inspect created objects by running:
$ kubectl get --namespace=scott all
or 
$ mlt status

(.venv) $ mlt status
NAME                                                       READY     STATUS    RESTARTS   AGE       IP           NODE
scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-master     1/1       Running   0          3m        10.24.2.11   gke-dls-interns-02-default-pool-c679f441-n44l
scott-unet-c2526c76-b048-4fa8-b856-c2f728cd142c-worker-0   0/2       Pending   0          3m        <none>       <none>
```

**Comment by scttl** [comment]
I don’t have a problem with unet, it’s with dist-resnet. Tried in a clean
python3 containerized environment and I get the same issue there.

**Comment by scttl** [comment]
Finally dug into this and figured out what was going on.  The template substitution literally considers everything in `k8s-templates` regardless of file type.  In my case I still had the template open in my editor in another window and the substitution was trying to pick up and substitute my `.job.yaml.swp` file (which isn't pure ASCII).  

Didn't catch it when I went with the clean containerized environment because I was mounting my host dir (with the .swp file in it).

Tried again after closing the file from my editor and it worked, so feel free to close this issue, though I'd recommend maybe tightening up the substitution requirements (e.g. only files that end in `.yaml`, no dot files)

**Comment by s1113950** [comment]
👍 thanks for digging into this!

**Comment by ashahba** [comment]
@scttl thanks for the detailed bug report.
I can now reproduce the issue.
I'll work on a fix for this but I guess for now I'm going to reduce the priority to `medium` since you are unblocked.
