### ISSUE TITLE
mlt undeploy backwards compatibility is broken

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#436]
```
robertso@robertso-mac02:/tmp/wat$ mlt undeploy --job-name wat-60583ba9-93bc-43c5-ac53-602a6a09593a
robertso@robertso-mac02:/tmp/wat$ mlt status
Job: wat-89676d81-78d8-43c2-bd12-efff4c10652f -- Creation Time: 2018-09-14 21:30:50+00:00
No resources found.
```
```
robertso@robertso-mac02:/tmp/wat$ mlt undeploy
Error from server (NotFound): error when stopping "k8s/wat-89676d81-78d8-43c2-bd12-efff4c10652f/job.yaml": jobs.batch "wat-89676d81-78d8-43c2-bd12-efff4c10652f" not found
Traceback (most recent call last):
  File "/Users/robertso/Nervana/mlt/.venv3/bin/mlt", line 11, in <module>
    load_entry_point('mlt==0.3.0+3.g5c5c414', 'console_scripts', 'mlt')()
  File "/Users/robertso/Nervana/mlt/mlt/main.py", line 213, in main
    run_command(args)
  File "/Users/robertso/Nervana/mlt/mlt/main.py", line 134, in run_command
    CommandClass(args).action()
  File "/Users/robertso/Nervana/mlt/mlt/commands/undeploy.py", line 60, in action
    self._undeploy_jobs(namespace, jobs, all_jobs=True)
  File "/Users/robertso/Nervana/mlt/mlt/commands/undeploy.py", line 86, in _undeploy_jobs
    raise_on_failure=True)
  File "/Users/robertso/Nervana/mlt/mlt/utils/process_helpers.py", line 31, in run
    raise e
  File "/Users/robertso/Nervana/mlt/mlt/utils/process_helpers.py", line 28, in run
    output = check_output(command, cwd=cwd).decode("utf-8")
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--namespace', 'robertso', 'delete', '-f', 'k8s', '--recursive']' returned non-zero exit status 1.
```

I had 2 `hello-world` jobs, I undeployed one with the `--job-name` flag and then expected `mlt undeploy` without the job name flag to work as expected and got a traceback

**Comment by s1113950** [comment]
Discovered undeploying with `--job-name` flag actually undeploys every job... I'll fix this up
